let app = require('./app/config/server')
let texto = require('./modulo1')
let rotahome = require('./app/routes/home')
rotahome(app)
let rotaAdicionarUsuario = require('./app/routes/adicionar_usuario')
rotaAdicionarUsuario(app)
let rotaHistoria = require('./app/routes/historia')
rotaHistoria(app)
let rotaCursos = require('./app/routes/cursos')
rotaCursos(app)
let rotaProfessores = require('./app/routes/professores')
rotaProfessores(app)
app.listen(3000,function(){
    console.log(texto)
})
